platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: '8-jdk'

inputs:
  - name: apps-movie-fun-modernization-code
  - name: version

outputs:
  - name: build-output

run:
  path: bash
  args:
  - -exc
  - |
    cd apps-movie-fun-modernization-code
    ./gradlew build
    cp applications/movie-fun-app/build/libs/movie-fun-app-1.0.war ../build-output/movie-fun-app-$(cat ../version/number).war