platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: '8-jdk'

inputs:
  - name: apps-movie-fun-modernization-code
  - name: version

outputs:
  - name: build-output

run:
  path: bash
  args:
  - -exc
  - |

    cd apps-movie-fun-modernization-code
    ./gradlew build -x test
    for app in movie-fun-app album-service movie-service; do
      cp \
        applications/${app}/build/libs/${app}-1.0.war \
        ../build-output/${app}-$(cat ../version/number).war
    done
